from fastapi import FastAPI, HTTPException
from fastapi.staticfiles import StaticFiles
from starlette.responses import FileResponse
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from openai import OpenAI
import os
from dotenv import load_dotenv
from util import sanitize_input, print_blue, print_red
import sys
from io import StringIO
import json
import pandas

# Load environment variables from .env file
load_dotenv()


app = FastAPI()

# Mount the static directory
app.mount("/static", StaticFiles(directory="static"), name="static")

# Configure CORS
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],  # Adjust this to restrict allowed origins
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Load OpenAI API key from environment variable
client = OpenAI(
    # This is the default and can be omitted
    api_key=os.environ.get("OPENAI_API_KEY"),
)

# Define request and response models
class QueryRequest(BaseModel):
    prompt: str
    data: str = None

class QueryResponse(BaseModel):
    response: str
    
# Functions
    
# Generate Chart Function

def generate_chart(data, prompt):
    try:

        # Set your OpenAI API key
        prompt = f"""You are an AI Assistant. Here is some data:
                    {data}

                    Using this data, make a chart that pertains to the following user prompt. 
                    

                     If the following prompt is not relevant to the data, respond with a lowercase "no". 
                     Any prompt that is not specifically asking for a piece of data relevant to the chart should be responded to with a no. 
                     This includes casual conversation, asking about other data sets, etc. Otherwise, Return a string that can be directly parsed by JSON.parse() with no other information except the vega lite specs. Don't make the height or width greater than 400px. Only return one chart no matter what.

                     {prompt}
                     """,
        print(prompt)
        # Call the OpenAI API via LangChain
        chat_completion = client.chat.completions.create(
            messages=[
                {
                    "role": "user",
                    "content": f"{prompt}",
                }
            ],
            model="gpt-4o-mini",
        )
        print(chat_completion)
        print("Returning Generated Chart")
        return chat_completion.choices[0].message.content
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))
    
    
# Data Analysis Function

def execute_panda_dataframe_code(code):
    """
    Execute the given python code and return the output. 
    References:
    1. https://github.com/langchain-ai/langchain-experimental/blob/main/libs/experimental/langchain_experimental/utilities/python.py
    2. https://github.com/langchain-ai/langchain-experimental/blob/main/libs/experimental/langchain_experimental/tools/python/tool.py
    """
     # Save the current standard output to restore later
    old_stdout = sys.stdout
    # Redirect standard output to a StringIO object to capture any output generated by the code execution
    sys.stdout = mystdout = StringIO()
    try:
		    # Execute the provided code within the current environment
        cleaned_command = sanitize_input(code)
        exec(cleaned_command)
        
        # Restore the original standard output after code execution
        sys.stdout = old_stdout
				
				# Return any captured output from the executed code
        return mystdout.getvalue()
    except Exception as e:
        sys.stdout = old_stdout
        return repr(e)



# ReAct Tool Calling Loop
def query(question : str, data : str, max_iterations = 10):
    print(data)
    print(question)
    system_prompt = "You are an AI Assistant. The user will give you some data and ask you a question. If the question is not relevant to the data, respond with only 'no'. It can either involve data analysis, chart generation, or both. You will return a dictionary of the form {chart : [VegaLite Chart as JSON], analysis : [Markdown as a string of any analysis or chart description that can be rendered with <ReactMarkdown remarkPlugins={[remarkGfm]}>{message}</ReactMarkdown>]}. The VegaLite chart will always be generated with the generate_chart tool, but the analysis Mardkwon can either be done by executing python code using the tool, or just a description of the chart of no analysis is required. This is very important: Remember that whenever you are using the execute pandas datafrom tool, the code must print out any results for it to be captured using the python print(...) function! No matter what, a dictionary of the form {chart : [VegaLite Chart as JSON or null], analysis : [Markdown of any analysis or chart description that can be rendered with <ReactMarkdown remarkPlugins={[remarkGfm]}>{message}</ReactMarkdown>]}, must be returned, and if you are just returning a markdown as a string include it in the analysis key. If the user doesn't explicitly ask for a graph, you can assume one will not be included. Remember, analysis must be a markdown string. It cannot be anything else, html, etc." 
    messages = [{"role": "system", "content": system_prompt}]
    messages.append({"role": "user", "content": "Here is the data:"  + data + "\n here is the question: " + question})
    i = 0
    while i < max_iterations:
        i += 1
        print("iteration:", i)
        response = client.chat.completions.create(
            model="gpt-4o-mini", temperature=0.0, messages=messages, tools=tools
        )

        if response.choices[0].message.content != None:
            print_red(response.choices[0].message.content)


        # if not function call
        if response.choices[0].message.tool_calls == None:
            break

        # if function call
        messages.append(response.choices[0].message)
        for tool_call in response.choices[0].message.tool_calls:
            print_blue("calling:", tool_call.function.name, "with", tool_call.function.arguments)
            # call the function
            arguments = json.loads(tool_call.function.arguments)
            function_to_call = tool_map[tool_call.function.name]
            result = function_to_call(**arguments)


            # create a message containing the result of the function call
            result_content = json.dumps({**arguments, "result": result})
            function_call_result_message = {
                "role": "tool",
                "content": result_content,
                "tool_call_id": tool_call.id,
            }
            print_blue("action result:", (result_content))

            messages.append(function_call_result_message)
        if i == max_iterations and response.choices[0].message.tool_calls != None:
            print_red("Max iterations reached")
            return "The tool agent could not complete the task in the given time. Please try again."
    return response.choices[0].message.content




# Endpoints



# Endpoint to interact with OpenAI API via LangChain
@app.post("/generateChart", response_model=QueryResponse)
async def generate_chart_endpoint(request: QueryRequest):
    return generate_chart(request.data, request.prompt)

@app.post("/query", response_model=QueryResponse)
async def query_endpoint(request: QueryRequest):
    query_response = query(request.prompt, request.data, 10)
    print("Printing Query")
    print(query_response)
    return QueryResponse(response=query_response)

# Root endpoint
@app.get("/")
async def read_root():
    return FileResponse('static/index.html')



# Descriptions

# Generate Chart Function 



# Define the tools and their mappings
tools = [
    {
        "type": "function",
        "function": {
            "name": "generate_chart",
            "description": "Takes a dataset and a user prompt that is related to the dataset. Based on the prompt, it returns a chart related to both the prompt and the dataset.",
            "type" : "generate_chart_description",
            "parameters": {
                "type": "object",
                "properties": {
                    "data": {
                        "type": "string",
                        "description": "The dataset",
                    },
                    "prompt": { 
                        "type": "string",
                        "description": "The user's prompt that is related to the dataset",
                    }
                },
                "required": ["data", "prompt"],
                "additionalProperties": False,
            }           
        }
    }, 
     {
        "type": "function",
        "function": {
            "name": "execute_panda_dataframe_code",
            "description": "Executes Python code, returning the output. The function captures output using print(...) statements.",
            "parameters": {
                "type": "object",
                "properties": {
                    "code": {
                        "type": "string",
                        "description": "The code that will be executed",
                    }
                },
                "required": ["code"],
                "additionalProperties": False,
            }
        } 
    }, 
]
tool_map = {
    "generate_chart": generate_chart,
    "execute_panda_dataframe_code": execute_panda_dataframe_code,
}
